---

master:
  hosts:
    master-01:
      ansible_host: 10.5.94.117
      ansible_user: pirate
      ansible_connection: ssh
workers:
  hosts:
      worker-02:
        ansible_host: 10.5.94.107
        ansible_user: pirate
        ansible_connection: ssh
