master:
  hosts:
    master-01:
      ansible_host: 10.5.94.51

workers:
  hosts:
    worker-02:
      ansible_host: 10.5.94.52
    worker-03:
      ansible_host: 10.5.94.53
    worker-04:
      ansible_host: 10.5.94.54
    worker-05:
      ansible_host: 10.5.94.55
    worker-06:
      ansible_host: 10.5.94.56
    worker-07:
      ansible_host: 10.5.94.57

node:
  children:
    workers:

k3s_cluster:
  children:
    master:
    node:


localkubectl:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
