---

master:
  hosts:
    master-01:
      ansible_host: 10.5.94.51
      ansible_user: pirate
      ansible_connection: ssh


workers:
  hosts:
      worker-02:
        ansible_host: 10.5.94.52
        ansible_user: pirate
        ansible_connection: ssh
      worker-03:
        ansible_host: 10.5.94.53
        ansible_user: pirate
        ansible_connection: ssh
      worker-04:
        ansible_host: 10.5.94.54
        ansible_user: pirate
        ansible_connection: ssh
      worker-05:
        ansible_host: 10.5.94.55
        ansible_user: pirate
        ansible_connection: ssh
      worker-06:
        ansible_host: 10.5.94.56
        ansible_user: pirate
        ansible_connection: ssh
      worker-07:
        ansible_host: 10.5.94.57
        ansible_user: pirate
        ansible_connection: ssh
