master:
  hosts:
    master-01:
      ansible_host: 10.10.42.51

workers:
  hosts:
    worker-02:
      ansible_host: 10.10.42.52
    worker-03:
      ansible_host: 10.10.42.53
    worker-04:
      ansible_host: 10.10.42.54
    worker-05:
      ansible_host: 10.10.42.55
    worker-06:
      ansible_host: 10.10.42.56
    worker-07:
      ansible_host: 10.10.42.57

localkubectl:
  hosts:
    localhost:
      ansible_host: 127.0.0.1

localimageflashcards:
  hosts:
    localhost:
      ansible_host: 127.0.0.1

ha-master-02:
  hosts:
    master-02:
      ansible_host: 10.10.42.41

#repairhosts:
#  hosts:
#    worker-07:
#      ansible_host: 10.10.42.17

node:
  children:
    workers:

k3s_cluster:
  children:
    master:
    node:
