---
- name: Deploy TP Cluster for k3s Sturgeon Technologies
  hosts: k3s_cluster
  gather_facts: yes
  become: true
  tasks:
    - name: Print all available facts
      debug:
        var: ansible_facts
      tags: ['never', 'debug']

    - name: Check var inventory_hostname
      debug: var=inventory_hostname
      tags: ['never', 'debug']

    - name: Print all hostvars
      debug: var=hostvars
      tags: ['never', 'debug']

    - name: Release
      debug: msg="{{ ansible_distribution_release }}"
      tags: ['never', 'os_info']

    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
      tags: ['never', 'os_info']

    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
      tags: ['never', 'os_info']

    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
      tags: ['never', 'os_info']

    - name: Get OS Name
      shell: cat {{ ansible_distribution_file_path }}
      register: os_name
      ignore_errors: yes
      tags: ['never', 'os_info']

    - name: Check OS Name
      debug: msg="{{os_name.stdout}}"
      tags: ['never', 'os_info']

  roles:
    - {role: bootstrap-core, tags: ['base']}
    - {role: docker, tags: ['docker']}

- hosts: master-02*
  roles:
    - {role: docker-registry, tags: ['docker-registry']}

- hosts: localhost
  connection: local
  roles:
    - {role: k8s-sturgeon, tags: ['k8s_core']}
  environment:
    KUBECONFIG: '~/.kube/config:~/.kube/kubconfig2'
