---
- hosts: localimageflashcards
  connection: local
  roles:
    - {role: image-flashcards, tags: ['image-flashcards']}

- hosts: repairhosts
  connection: ssh
  roles:
    - {role: image-flashcards, tags: ['image-flashcards']}
