---

# tasks file for bootstrap-core
# template out /boot/user-data so cloud-init can be rerun if needed.
- name: template /boot/user-data
  template:
    src: user-data.j2
    dest: "{{cf_mount_boot}}/user-data"
  tags: local-cloud-init-cfg

# change /boot/config.txt and /boot/cmdline.txt as needed
- name: Copy config.txt to boot
  copy:
    src: config.txt
    dest: "{{cf_mount_boot}}/config.txt"
    remote_src: no
  tags: local-boot-config

- name: Copy cmdline.txt to boot
  copy:
    src: cmdline.txt
    dest: "{{cf_mount_boot}}/cmdline.txt"
    remote_src: no
  tags: local-boot-cmdline

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: "{{cf_mount_root}}/etc/hosts"
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{ hostvars[item].nic_name }}"
    state: present
  become: yes
  when: hostvars[item].ansible_host and hostvars[item].nic_name is defined
  with_items: "{{ groups.all }}"
  tags: local-add_hosts

- name: Activating cgroup support
  lineinfile:
    path: "{{cf_mount_boot}}/cmdline.txt"
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  tags: local-add_cgroup

